apiVersion: v1
kind: Secret

metadata:
  name: todo-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
  DB_USER: {{ .Values.postgres.credentials.username | quote }}
  DB_PASSWORD: {{ .Values.postgres.credentials.password | quote }}
