apiVersion: v1
kind: Pod

metadata:
  name: todo-frontend
  namespace: todo
  labels:
    app: todo-frontend

spec:
  containers:
    - name: nginx
      image: todo-app-frontend:latest
      imagePullPolicy: IfNotPresent

      ports:
        - containerPort: 80